[project]
name = "meowDFer"
version = "0.1.0"
description = "A CLI tool to convert zipped image folders into structured PDFs"
requires-python = ">=3.10"
authors = [
    {name = "v1c3nt"}
]

dependencies = [
    "Pillow", 
    "pypdf",
    "rich>=13.0.0"
]

[project.optional-dependencies]
dev = [
    "pytest"
]

[project.scripts]
meowdfer = "meowdfer:initiate"

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
norecursedirs = ["src"] 
python_files = ["test_*.py"]
python_functions = ["test_*"]